#ifndef __AFTERBURN_WEDGE__INCLUDE__RHYPE__CONFIG_H__
#define __AFTERBURN_WEDGE__INCLUDE__RHYPE__CONFIG_H__

#ifndef CONFIG_WEDGE_RHYPE
#define CONFIG_WEDGE_RHYPE
#endif
#define CONFIG_WEDGE	rhype

#endif	/* __AFTERBURN_WEDGE__INCLUDE__RHYPE__CONFIG_H__ */
