######################################################################
#                
# Copyright (C) 2005, University of Karlsruhe
#                
# File path:     patches/Makefile.patch
# Description:   Rules to build patches of external source projects.
#                
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#                
######################################################################

help-create-patch::
	@echo Patch creation:
	@echo "  create-patch"
	@echo "    create-patch-linux-2.6"
	@echo "    create-patch-linux-2.6-vmi"
	@echo "    create-patch-linux-2.4"
	@echo "    create-patch-xen-2"
	@echo "    create-patch-xen-3"
	@echo

untar_.gz  = -zxf
untar_.tgz = -zxf
untar_.bz2 = -jxf
untar_.bgz = -jxf

untar_opts = $(untar_$(suffix $(1)))

diff = env LC_ALL=C TZ=UTC0 diff -Naur
patch_test = patch --dry-run -Np1

create-patch-linux-2.6: $(ARCHIVE_DIR)/$(TARBALL_linux-2.6)
create-patch-linux-2.6-vmi: $(ARCHIVE_DIR)/$(TARBALL_linux-2.6-vmi)
create-patch-linux-2.4: $(ARCHIVE_DIR)/$(TARBALL_linux-2.4)
create-patch-xen-2: $(ARCHIVE_DIR)/$(TARBALL_xen-2)
create-patch-xen-3: $(ARCHIVE_DIR)/$(TARBALL_xen-3)

create-pristine = echo "Creating $(SRCDIR)/$(UNPACK_$(1)).pristine" \
    && if [ ! "-d $(SRCDIR)/$(UNPACK_$(1)).pristine" ] ; \
    then mkdir -p $(SRCDIR)/$(UNPACK_$(1)).pristine \
    && cd $(SRCDIR)/$(UNPACK_$(1)).pristine \
    && tar --strip-components=1 $(call untar_opts,$(TARBALL_$(1))) $(ARCHIVE_DIR)/$(TARBALL_$(1)) \
    ; fi

create-patch = echo "Creating $(UNPACK_$(1)).patch" \
    && cd $(SRCDIR) \
    && $(diff) $(UNPACK_$(1)).pristine $(UNPACK_$(1)) > $(CURDIR)/$(UNPACK_$(1)).patch \
    ; echo "Testing $(UNPACK_$(1)).patch" \
    && cd $(UNPACK_$(1)).pristine \
    && $(patch_test) < $(CURDIR)/$(UNPACK_$(1)).patch

create-patch-%:
	$(Q) $(call create-pristine,$*)
	$(Q) $(call create-patch,$*)
	@echo "Finished $@"

