#ifndef __AFTERBURN_WEDGE__INCLUDE__WINNT__CONFIG_H__
#define __AFTERBURN_WEDGE__INCLUDE__WINNT__CONFIG_H__

#ifndef CONFIG_WEDGE_WINNT
#define CONFIG_WEDGE_WINNT
#endif
#define CONFIG_WEDGE	winnt

#endif	/* __AFTERBURN_WEDGE__INCLUDE__WINNT__CONFIG_H__ */
