
Q ?= @

all: Makefile

mk_dir := $(afterburn_dir)/Mk

##  Generate a valid configuration.
include $(mk_dir)/Makefile.cml
include config.out

##  Only include the remaining build logic if we have a valid configuration.
ifeq ($(cfg_cml),y)
include $(mk_dir)/Makefile.world
endif

##  Generate a Makefile in the build directory.
Makefile:
	@echo "include $(afterburn_dir)/Makefile" > Makefile
	@echo "Your settings are now cached in Makefile"

