#ifndef __AFTERBURN_WEDGE__INCLUDE__LINUX__CONFIG_H__
#define __AFTERBURN_WEDGE__INCLUDE__LINUX__CONFIG_H__

#ifndef CONFIG_WEDGE_LINUX
#define CONFIG_WEDGE_LINUX
#endif
#define CONFIG_WEDGE linux

#endif	/* __AFTERBURN_WEDGE__INCLUDE__LINUX__CONFIG_H__ */
