#ifndef __AFTERBURN_WEDGE__INCLUDE__XEN__CONFIG_H__
#define __AFTERBURN_WEDGE__INCLUDE__XEN__CONFIG_H__

#ifndef CONFIG_WEDGE_XEN
#define CONFIG_WEDGE_XEN
#endif
#define CONFIG_WEDGE xen

#endif	/* __AFTERBURN_WEDGE__INCLUDE__XEN__CONFIG_H__ */

